export const msgServerError = 'Server interval';
export const msgNotFound = 'The document not found';
export const msgValidateEmail = 'Email not correct format';

export const msgResponse = {
  createAttachment: 'Create attachment success',
  getByIdAttachment: 'Get attachment success',
  deleteAttachment: 'Delete attachment success',
  notFoundAttachment: 'Attachment not found',
  initSupperAdminAuth: 'Create supper admin success',
  loginAuth: 'Login sucess',
  getMeAuth: 'Get me success',
  errorAuth: 'User or password incorrect',
  createAward: 'Create award success',
  updateAward: 'Update award success',
  getByIdAward: 'Get award by Id sucess',
  getAllAward: 'Get all award success',
  createBranch: 'Create branch success',
  getAllBranch: 'Get all branchs success',
  updateBranch: 'Update branch success',
  getByIdBranch: 'Get branch by id success',
  createCenter: 'Create center success',
  getAllCenter: 'Get all centers success',
  updateCenter: 'Update center success',
  getByIdCenter: 'Get center by id success',
  deleteCenter: 'Delete center success',
  createClass: 'Create class success',
  updateClass: 'Update class success',
  getByIdClass: 'Get class by id success',
  getAllClass: 'Get all classes success',
  createSubject: 'Create subject success',
  updateSubject: 'Update subject success',
  getByIdSubject: 'Get subject by id success',
  createSubjectProcessError: 'Can not create subject process',
  initCountries: 'Import multi countries success',
  getAllCountries: 'Get all countries success',
  getByIdCountry: 'Get country by id success',
  updateCountry: 'Update country success',
  initProvince: 'Import multi provinces success',
  getAllProvince: 'Get all provinces success',
  getAllDistrict: 'Get all districts success',
  initDistrict: 'Import multi districts success',
  initWard: 'Import multi wards success',
  getAllWard: 'Get all wards success',
  createCourse: 'Create course success',
  getAllCourse: 'Get all courses success',
  updateCourse: 'Update course success',
  getByIdCourse: 'Get course by id success',
  deleteCourse: 'Delete course success',
  createDegreelevel: 'Create degreelevel success',
  getAllDegreelevel: 'Get all degreelevels success',
  updateDegreelevel: 'Update degreelevel success',
  getByIdDegreelevel: 'Get degreelevel by id success',
  deleteDegreelevel: 'Delete degreelevel success',
  createDepartment: 'Create department success',
  getAllDepartment: 'Get all departments success',
  updateDepartment: 'Update department success',
  getByIdDepartment: 'Get department by id success',
  deleteDepartment: 'Delete department success',
  createDepartmentStaff: 'Create department staff success',
  createMultiStaff: 'Create department multi staff success',
  getAllDepartmentStaff: 'Get all departments staff success',
  updateDepartmentStaff: 'Update department staff success',
  getByIdDepartmentStaff: 'Get department staff by id success',
  deleteDepartmentStaff: 'Delete department staff success',
  createFaculty: 'Create faculty success',
  getAllFaculty: 'Get all faculties success',
  updateFaculty: 'Update faculty success',
  getByIdFaculty: 'Get faculty by id success',
  deleteFaculty: 'Delete faculty success',
  createMajor: 'Create major success',
  getAllMajor: 'Get all majors success',
  updateMajor: 'Update major success',
  getByIdMajor: 'Get major by id success',
  createInstitute: 'Create institute success',
  getAllInstitute: 'Get all institutes success',
  updateInstitute: 'Update institute success',
  getByIdInstitute: 'Get institute by id success',
  deleteInstitute: 'Delete institute success',
  createNews: 'Create news success',
  getAllNews: 'Get all news success',
  updateNews: 'Update news success',
  getByIdNews: 'Get news by id success',
  deleteNews: 'Delete news success',
  createMoneyCreditMgt: 'Create amount credit success',
  getAllMoneyCreditMgt: 'Get all amount credit success',
  updateMoneyCreditMgt: 'Update amount credit success',
  getByIdMoneyCreditMgt: 'Get amount credit by id success',
  createUserTuition: 'Create user tuition success',
  getAllUserTuition: 'Get user tuition success',
  createPermission: 'Create permission success',
  getAllPermission: 'Get all permission success',
  updatePermission: 'Update permission success',
  getByIdPermission: 'Get permission by id success',
  deletePermission: 'Delete permission success',
  createRoom: 'Create room success',
  getAllRoom: 'Get all room success',
  updateRoom: 'Update room success',
  getByIdRoom: 'Get room by id success',
  deleteRoom: 'Delete room success',
  createScholarship: 'Create sholarship success',
  updateScholarship: 'Update scholarship success',
  getAllScholarship: 'Get all scholarship success',
  createUserScholarship: 'Create user scholarship success',
  getAllUserScholarship: 'Get all user scholarship success',
  getByIdScholarship: 'Get scholarship by id success',
  createSchool: 'Create school success',
  getAllSchool: 'Get all school success',
  updateSchool: 'Update school success',
  getByIdSchool: 'Get school by id success',
  deleteSchool: 'Delete school success',
  createSemester: 'Create semester success',
  getAllSemester: 'Get all semester success',
  updateSemester: 'Update semester success',
  getByIdSemester: 'Get semester by id success',
  deleteSemester: 'Delete semester success',
  migrateUsersLibrary: 'Sync data success',
  getAllUserSyncLibrary: 'Get all users success',
  createUnion: 'Create union success',
  getAllUnion: 'Get all unions success',
  updateUnion: 'Update union success',
  getByIdUnion: 'Get union by id success',
  deleteUnion: 'Delete union success',
  createUser: 'Create user success',
  existedProfileUser: 'Profile of user existed already',
  createUserProcessFailed: 'Can not create study process',
  userProfileNotFound: 'User profile not found',
  leaderSchoolExisted: 'Leader school existed already',
  initSupperAdmin: 'Supper admin existed already',
  getAllUser: 'Get all user success',
  updateUser: 'Update user success',
  getByIdUser: 'Get user by id success',
  deleteUser: 'Delete user success',
  importUser: 'Import multi user success',
  updateUserProfile: 'Update profile success',
  createLeaderSchool: 'Create leader school success',
  getAllLeaderSchool: 'Get all leader school success',
  updateLeaderSchool: 'Update leader school success',
  getByIdLeaderSchool: 'Get leader school by id success',
  deleteLeaderSchool: 'Delete leader school success',
};

export const descriptionResponse = {
  apiLogin: 'Response data when login success',
  apiGetMe: 'Response data when get me success',
  apiInitAdmin: 'Response data when create supper admin success',
  apiUpdateUser: 'Response data when create update user success',
  apiUpdateProfile: 'Response data when update user profile success',
  apiGetAllUser: 'Response data when get all user success',
  apiGetUserById: 'Response data when get user by id success',
};

export const msgImportUser = {
  validateFields:
    'email or passWord or role or firstName or lastName must provided.',
  createUserFailed: 'Can not create user',
  createProfileFailed: 'Can not create profile',
  createStudyProcessFailed: 'Can not create study process',
  statusSuccess: 'Import user success',
};
